print("Name: Sharafat Hossain")
print("Age: 25")
print("Location: Dhaka, Bangladesh")
print("Occupation: Software Engineer")
print("Hobbies: Coding, Reading, Traveling")
print("Favorite Language: Python")
print("Favorite Framework: Flask")
print("Favorite Database: PostgreSQL")
print("Favorite IDE: Visual Studio Code")